[theme]
base = "light"

# Primary accent color for interactive elements
primaryColor = "#2563EB"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#F1F5F9"

# Color used for almost all text
textColor = "#1E293B"

# Font family for all text in the app, except code blocks
font = "sans serif" 